name: Trigger Jira Webhook

on:
  push:
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Jira Webhook
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://example.com/rest/webhooks/webhook1'
          method: 'POST'
          contentType: 'application/json'
          data: '{"message": "GitHub Action Triggered"}'
